language: generic
dist: trusty
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
sudo: true

install:
  sudo pip3 install --pre homotopy

script:
  - curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh
